service: justify-me
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  handler:
    handler: src/handler.handler
    environment:
      TOKENS_RATE_LIMIT_TIMEOUT: 86400000
      TOKENS_MAX_REQUEST: 1
      JUSTIFY_WORD_LIMIT: 80000
      JWT_SECRET: "superSecretJWT"
      DYNAMODB_TABLE_NAME: "TokensRateLimit"
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

plugins:
  - "serverless-plugin-typescript"
  - "serverless-offline"
